### PR TITLE
Improve index.js

### PR DESCRIPTION
**Pull request by Tabrizian**
Hi,

What's your idea of the passing server to every callback so that you can use the server plugin inside your callbacks?

### CODE REVIEW

**Comment by 1995parham** [comment]
🤔 I think it is a good idea and you even pass server into validator?

**Comment by Tabrizian** [comment]
No, only its used in the callbacks of subscription you can refer to Bambil project for use cases :))

**Comment by Tabrizian** [comment]
My mistake. I'll fix it right now

**Comment by 1995parham** [comment]
Thanks for your improvement 👍

**Pull request merged**
